// Generated by CoffeeScript 1.3.3
/*
 Ace Editor in your browser!
 Code Mirror coming soon!
 
 @example <div ace syntax="'json'" ng-model="current_object.text"></div> // must have explicit width
 @author nickretallack 
 @link https://github.com/nickretallack/Visual-Language/blob/master/stuff.coffee
 @param syntax {expression} the syntax language (must evaluate to a string that matches the filename of the IDE mode) json|js|html|css|etc
 @param ngModel {expression} the model to store the results into
*/

angular.module('ui.directives').directive('uiIde', [
  'ui.config', function(uiConfig) {
    var options;
    options = {};
    if (uiConfig.ide != null) {
      angular.extend(options, uiConfig.ide);
    }
    return {
      require: '?ngModel',
      link: function(scope, element, attributes, ngModel) {
        var JavaScriptMode, changing, editor, opts, read, session, syntax;
        opts = angular.extend({}, options, scope.$eval(attrs.uiIde));
        editor = ace.edit(element[0]);
        session = editor.getSession();
        syntax = scope.$eval(attributes.syntax);
        if (syntax && syntax !== 'plain') {
          JavaScriptMode = require("ace/mode/" + syntax).Mode;
          session.setMode(new JavaScriptMode());
        }
        if (!ngModel) {
          return;
        }
        changing = false;
        ngModel.$render = function() {
          changing = true;
          session.setValue(ngModel.$viewValue || '');
          return changing = false;
        };
        read = function() {
          return ngModel.$setViewValue(session.getValue());
        };
        return session.on('change', function() {
          if (!changing) {
            return scope.$apply(read);
          }
        });
      }
    };
  }
]);
